### PR TITLE
Correct fix for hakari crashes

### LINKED ISSUE #255: `cargo hakari generate` crashed
When trying out `hakari`, I couldn't run the `generate` command.
Let me know if I can provide more info.

```
$ cargo hakari generate
The application panicked (crashed).
Message:  index out of bounds: the len is 7282 but the index is 7282
Location: ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/guppy-0.17.5/src/petgraph_support/topo.rs:49

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: color_eyre::config::PanicHook::into_panic_hook::{{closure}}::hbabd9e3254037d94
      at <unknown source file>:<unknown line>
   2: std::panicking::rust_panic_with_hook::hfd477be88114f3c4
      at <unknown source file>:<unknown line>
   3: std::panicking::begin_panic_handler::{{closure}}::hb957e98065a4568c
      at <unknown source file>:<unknown line>
   4: std::sys_common::backtrace::__rust_end_short_backtrace::ha9a82577e2e3f0de
      at <unknown source file>:<unknown line>
   5: rust_begin_unwind<unknown>
      at <unknown source file>:<unknown line>
   6: core::panicking::panic_fmt::h281c4bbb02f68665
      at <unknown source file>:<unknown line>
   7: core::panicking::panic_bounds_check::h975aed5e94c0faa6
      at <unknown source file>:<unknown line>
   8: guppy::petgraph_support::topo::TopoWithCycles<Ix>::new::h96c0455e22f74fde
      at <unknown source file>:<unknown line>
   9: once_cell::imp::OnceCell<T>::initialize::{{closure}}::ha03be1ce336e21ab
      at <unknown source file>:<unknown line>
  10: once_cell::imp::initialize_or_wait::hd5d8d656a2a768a3
      at <unknown source file>:<unknown line>
  11: once_cell::imp::OnceCell<T>::initialize::h49bb92dc6e588fbb
      at <unknown source file>:<unknown line>
  12: guppy::graph::feature::resolve::FeatureSet::root_ids::he4960f4645d3e97f
      at <unknown source file>:<unknown line>
  13: <alloc::collections::btree::map::ExtractIf<K,V,F,A> as core::iter::traits::iterator::Iterator>::next::hd7438f48ef318cf5
      at <unknown source file>:<unknown line>
  14: hakari::hakari::Hakari::build::he98dd6651e40e84a
      at <unknown source file>:<unknown line>
  15: cargo_hakari::command::Command::exec::hdc1c66fe7fdfa045
      at <unknown source file>:<unknown line>
  16: cargo_hakari::main::hf4a74d35af379ec9
      at <unknown source file>:<unknown line>
  17: std::sys_common::backtrace::__rust_begin_short_backtrace::h5d74b18ad36c9ab3
      at <unknown source file>:<unknown line>
  18: std::rt::lang_start::{{closure}}::h0234ee382a08a736
      at <unknown source file>:<unknown line>
  19: std::rt::lang_start_internal::h7d9fe2c277f41ab2
      at <unknown source file>:<unknown line>
  20: main<unknown>
      at <unknown source file>:<unknown line>
  21: __libc_start_main<unknown>
      at <unknown source file>:<unknown line>
  22: _start<unknown>
      at <unknown source file>:<unknown line>
```

### PR DESCRIPTION
**Pull request by sunshowers**
This is the real fix for these crashes. Also add a bunch of tests.

Fixes #255.

### CODE REVIEW

File: guppy/src/graph/feature/build.rs [hunk 1]
```diff
@@ -153,7 +155,21 @@ impl FeatureGraphBuildState {
...
+                    // will also activate the named feature `hyper`.
+                    //
+                    // One thing to be careful of here is that we don't want to insert self-edges.
+                    // For example:
+                    //
+                    // tokio = ["dep:tokio", "tokio/net"]
+                    //
+                    // should not insert a self-edge from `tokio` to `tokio`. The second condition
+                    // checks this.
+                    if !*weak && &**dep_name != from_named_feature {
```
Comment (sunshowers) [inline guppy/src/graph/feature/build.rs:172]: This is the fix.
